# Site settings
title: PanMin Blog
SEOTitle: 潘珉的博客 | PanMin Blog
header-img: img/home-bg.jpg
email: panminzzu@126.com
description: "潘珉，Android、Java、Node.js、C#  | 这里是 @panmin潘珉 的个人博客。"
keyword: "潘珉, panmin潘珉, panmin, Mr_PanMin, @潘珉, 潘珉的博客, panmin Blog, 博客, 个人网站, 互联网, 安卓, 人工智能, 蓝牙, 腕投"
url: "https://panmin.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     Mr_Panmin
zhihu_username:     panmin
github_username:    panmin
#twitter_username:  panmin
#facebook_username:  panmin
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: panmin

# Duoshuo settings
#duoshuo_username: panmin
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Coding..Coding...Coding...."
sidebar-avatar: /img/user_header.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "name",  #name
#        href: "url"     #home url
#    }
#]
